import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Navbar from "~/components/Navbar";
import { useRouter } from "next/router";

import { ChevronLeftIcon } from "@heroicons/react/24/solid";

import data from "~/data.json";

import { api } from "~/utils/api";
import { Status } from "~/components/Invoice";

const Invoice: NextPage = () => {
  const router = useRouter();

  const id = router.query.id;

  const handleReturn = () => {
    router.back();
  };

  const invoice = data.filter((invoice) => invoice.id === id)[0];
  console.log(invoice);
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col bg-secondaryBlack">
        <div
          className="flex items-center space-x-2 px-6 pt-8"
          onClick={handleReturn}
        >
          <ChevronLeftIcon className="h-3 w-3 text-primaryPurple" />
          <span className="text-xs font-bold tracking-[-0.25px] text-white">
            Go back
          </span>
        </div>

        <div className="flex w-full flex-col px-6 pt-4">
          {/* Status */}
          <div className="w-full rounded-lg bg-primaryDarkBlue px-6 py-9">
            <div className="flex w-full items-center justify-between">
              <p className="text-xs text-white">Status</p>

              <Status status={invoice!.status} />
            </div>
          </div>

          {/* Invoice inFo */}
          <div className="mt-4 flex w-full flex-col rounded-lg bg-primaryDarkBlue p-6">
            <div className="">
              <div className="flex w-full flex-col justify-between md:flex-row md:items-center">
                <div className="flex flex-col">
                  <h1 className="text-xs font-bold text-white">
                    <span className="text-xs font-bold text-wildBlue">#</span>
                    {invoice?.id}
                  </h1>
                  <p className="text-xs font-medium text-lavender">
                    {invoice?.description}
                  </p>
                </div>

                <div className="text-[11px] font-medium tracking-[-0.23px] text-lavender">
                  <div className="item mt-6 flex flex-col">
                    <p className="text-xs font-medium leading-[18px] tracking-[-0.23px] text-lavender">
                      {invoice?.senderAddress.street}
                    </p>
                    <p className="text-xs font-medium leading-[18px] tracking-[-0.23px] text-lavender">
                      {invoice?.senderAddress.city}
                    </p>
                    <p className="text-xs font-medium leading-[18px] tracking-[-0.23px] text-lavender">
                      {invoice?.senderAddress.postCode}
                    </p>
                    <p className="text-xs font-medium leading-[18px] tracking-[-0.23px] text-lavender">
                      {invoice?.senderAddress.country}
                    </p>
                  </div>
                </div>
              </div>

              <div className="mt-8 flex w-full flex-col justify-between md:flex-row">
                <div className="flex w-full">
                  <div>
                    <div className="flex flex-col">
                      <p className="text-xs font-medium text-lavender">
                        Invoice
                      </p>
                      <p className="mt-3 text-base font-bold leading-5  text-lavender">
                        {invoice?.createdAt}
                      </p>
                    </div>
                    <div className="mt-8">
                      <p className="text-xs font-medium leading-4 text-lavender">
                        Payment Due
                      </p>
                      <p className="mt-3 text-base font-bold leading-5 text-lavender">
                        {invoice?.paymentDue}
                      </p>
                    </div>
                  </div>
                  <div className="ml-10 flex flex-col md:ml-24">
                    <p className="text-xs font-medium text-lavender">Bill To</p>
                    <div className="mt-3 flex flex-col">
                      <p className="text-base font-bold leading-5 text-lavender">
                        {invoice?.clientName}
                      </p>
                      <div className="mt-">
                        <p className="text-xs font-medium leading-[18px] tracking-[-0.23px] text-lavender">
                          {invoice?.clientAddress.street}
                        </p>
                        <p className="text-xs font-medium leading-[18px] tracking-[-0.23px] text-lavender">
                          {invoice?.clientAddress.city}
                        </p>
                        <p className="text-xs font-medium leading-[18px] tracking-[-0.23px] text-lavender">
                          {invoice?.clientAddress.postCode}
                        </p>
                        <p className="text-xs font-medium leading-[18px] tracking-[-0.23px] text-lavender">
                          {invoice?.clientAddress.country}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="mt-8 md:mr-24 md:mt-0">
                  <p className="text-xs font-medium text-lavender">Sent To</p>
                  <div className="mt-3 flex flex-col">
                    <p className="text-base font-bold leading-5 text-lavender">
                      {invoice?.clientEmail}
                    </p>
                  </div>
                </div>
              </div>
            </div>
            {/* Items */}
            <div className="mt-10 flex w-full flex-col">
              <div className="flex flex-col rounded-t-lg bg-[#252945] p-6 ">
                {/* Item */}
                {invoice?.items.map((item) => (
                  <div className="mb-6" key={item.name}>
                    <div className="flex w-full items-center justify-between">
                      <div className="flex flex-col">
                        <p className="text-xs font-bold  leading-4 tracking-[-0.25px] text-white">
                          {item.name}
                        </p>
                        <span className="mt-2 text-xs font-bold leading-4 tracking-[-0.25px] text-coolGray">
                          {item.quantity} x {item.price}
                        </span>
                      </div>
                      <div className="">
                        <p className="text-xs font-bold leading-4 tracking-[-0.25px] text-white">
                          {/* euro*/}€{item.total}
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              <div className="rounded-b-lg bg-[#0C0E16] px-6 py-8">
                <div className="flex w-full items-center justify-between">
                  <p className="text-xs leading-[18px] tracking-[-0.25px] text-white">
                    Amount Due
                  </p>
                  <p className="text-xl font-bold leading-8 tracking-[-0.42px] text-white">
                    € {invoice?.total.toFixed(2)}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-14 flex w-full justify-center space-x-6 bg-primaryDarkBlue px-6 py-5">
          <button className="rounded-full  bg-secondaryDarkBlue px-6 py-4 text-xs font-bold text-lavender">
            Edit
          </button>
          <button className="rounded-full bg-primaryRed px-6 py-4 text-xs font-bold text-white">
            Delete
          </button>
          <button className="rounded-full bg-primaryPurple px-7 py-4 text-xs font-bold leading-4 text-white">
            Mark as Paid
          </button>
        </div>
      </main>
    </>
  );
};

export default Invoice;
